AWSTemplateFormatVersion: 2010-09-09
Description: Use an existing "fortune-ami" to launch an EC2 instance, and put it in an autoscaling group so one VM always exists.

Parameters:
  CustomAMI: 
    Type: String
    Description: Enter your custom "fortune-ami"

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access via port 80
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0

  LaunchConfigurationConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref CustomAMI
      SecurityGroups:
        - !Ref WebServerSecurityGroup
      InstanceType: t2.micro
      KeyName: EC2keypair # change to match your own settings
      UserData: !Base64 |
        #!/bin/bash -xe
        service httpd start
      BlockDeviceMappings:
        - DeviceName: /dev/sda1 #root EBS
          Ebs:
            VolumeSize: 8
            VolumeType: gp2

  AutoScalingConfig:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones: 
        - ap-northeast-1a
      LaunchConfigurationName: !Ref LaunchConfigurationConfig
      DesiredCapacity: 1
      MinSize: 1
      MaxSize: 1