AWSTemplateFormatVersion: 2010-09-09
Description: Deploy a EC2 VM and host a simple static "Fortune-of-the-Day Coming Soon" web page.

Resources:
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0a1c2ec61571737db # ap-northeast-1
      InstanceType: t2.micro # free tier
      SecurityGroups: 
        - !Ref WebServerSecurityGroup
      KeyName: EC2keypair # change to match your own settings
      UserData: !Base64 |
        #!/bin/bash -xe
        yum update -y
        yum install httpd -y
        service httpd start
        echo "<html><body>Fortune-of-the-Day Coming Soon</body></html>" > /var/www/html/index.html

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access via port 80
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0